- src/main.rs
- src/request.rs
- src/subscribe.rs
- src/subscribe/tests.rs
`static`으로 선언된 `RUNTIME_POLICY_LIST`를 없애고 일반 변수로 대체합니다.
> Avoid using a global variable

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- src/request.rs
- src/settings.rs
- src/subscribe.rs
- src/subscribe/tests.rs
- tests/config.toml
- Removes the agent_id provided by the argument. This value is provided by the certificate.
- Update quinn version to 0.10 and rustls version to 0.21 for giganto-client version to 0.7.0.
- Update review version to 0.22.0.
> Change use of `client_handshake` in oinq due to oinq version update

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/client.rs
- src/model.rs
- src/request.rs
- src/subscribe.rs
This PR is for a feature that is only used in rio projects.
- Change the `Interval`/`RequestedInterval` enum to include the new fields.
- Fix clippy error.
- Bump the new rio version 0.3.1+rio.0.0.1.
> Modify policy interval

- Cargo.lock
- Cargo.toml
- src/request.rs
- src/settings.rs
This pull request addresses the issue in `oinq` regarding its structure and modularity, as described in petabi/oinq#60. Currently, `oinq` serves as a comprehensive package for implementing the communication protocol within the REview ecosystem, relying on QUIC for efficient and secure communication. However, to promote code reuse and collaboration among projects utilizing QUIC, it's proposed to refactor `oinq` into two separate crates:
1. **`oinq`**: This crate will focus solely on low-level network communication, such as sending and receiving messages and streams.
2. **`review-protocol`**: Built on top of `oinq`, this crate will implement the application-specific protocol for the REview ecosystem.
This pull request implements the proposed changes by replacing direct dependencies on …
> Refactor dependencies to use review-protocol crate

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/client.rs
- src/main.rs
- src/request.rs
- src/settings.rs
- src/subscribe.rs
- src/subscribe/tests.rs
- Update quinn,rustls,review-protocol version.
- Fixed code related to updating depedenciese.
- Update the protocol version of the giganto ingest, publish.
- Changed the form of timeseries sent to giganto to `Vec<(i64,Vec<u8>)>`.
- Added a `Certs` to store commonly used certificate information.
Close: #84 #85
> Support giganto-client 0.17.0 & Change timeseries event sending format

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- src/request.rs
- src/settings.rs
- src/subscribe.rs
- src/subscribe/tests.rs
1. Update giganto-client to 0.20.0
- Add more network data type. (`Bootp`, `Dhcp`)
- Update the protocol version of the REview, giganto.
- Change `REVIEW_PROTOCOL_VERSION` to "0.38.0".
- Change `PUBLISH_PROTOCOL_VERSION` to "0.21.0".
- Change `INGEST_PROTOCOL_VERSION` to "0.21.0".
2. Update review-protocol version to 0.6.0
- Modify to use `ConnectionBuilder` to simplify the handling of connections with Central Manager.
- As `set_config` was removed from `review-protocol::request::handler`, Remove the `set_config` 
related code from the crusher.
Close: #96
Close: #98
> bump dependencies

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- src/request.rs
- src/settings.rs
- Changed `REVIEW_PROTOCOL_VERSION` to "0.39.0"
- Updated review-protocol to version "0.7.0".
- As `get_config` was removed from `review-protocol::request::handler`, Removed the `get_config` related code from the crusher.
Close: #101
> Update REview handshake compatible version & review-protocol version

- CHANGELOG.md
- src/request.rs
- src/subscribe.rs
- Changed `REVIEW_PROTOCOL_VERSION` to `REQUIRED_MANAGER_VERSION`.
- Used `REQUIRED_GIGANTO_VERSION` instead of names that include `INGEST` or `PUBLISH`.
Close: #105
> Correct how to refer to other required modules in the code

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/request.rs
- Change `REQUIRED_MANAGER_VERSION` to 0.39.0 because the version for quic communication with the manager server is 0.39.0.
Related issue: #122
> Bump version to 0.5.0

- src/request.rs
- src/subscribe.rs
This PR removes unnecessary `clone` calls in `src/subscribe.rs`. The `RequestedPeriod` enum now derives `Copy`, making the `clone` call in `calculate_series_start_time` redundant.
> Remove redundant `clone` call

- src/model.rs
- src/subscribe.rs
Replaced the use of `to_i64` method with direct conversion using `i64::from` for cleaner and more readable code.
> Remove unnecessary error handling for type conversions

- src/client.rs
- src/main.rs
- src/subscribe.rs
- src/subscribe/tests.rs
The `Certs` struct is not shared across threads, so the `Arc` is not needed.
> Remove unnecessary Arc usage for Certs

- src/model.rs
This PR simplifies the time slot calculation in `src/model.rs` by using the modulo operator (`%`) instead of manual calculation. This change improves code readability and maintainability without affecting the functionality.
> Simplify time slot calculation using modulo operator

- src/client.rs
This pull request removes an unnecessary `impl Clone` from the codebase. This change simplifies the code without causing any functional difference.
> Remove unnecessary `impl Clone`

- src/client.rs
This PR refactors the client endpoint address construction to use `Ipv6Addr::UNSPECIFIED` instead of parsing a string literal. This simplifies the code and avoids error handling.
No functional change is expected from this PR.
> Simplify endpoint address construction

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/request.rs
It depends on the manager version 0.42.0.
~This PR is in draft status because implementing a precedent task corresponding to [this commit](https://github.com/petabi/review-protocol/commit/07edf4dd23b8685a7d29a27510d3598898fc7d24) is required first.~
Close: #146
> Send the agent status to the Manager

- src/logging.rs
- src/main.rs
- src/request.rs
Previously, logging behavior depended on both `log_path` and the build type(debug/release). This commit removes the dependency on the build type. Logging is now controlled sololy by `log_path`.
- If `log_path` is specified, logs are sent to the file.
- If not, logs are sent to stdout.
Additionally, two macros are introduced: `error_or_eprint`, `info_or_print`. These replace the previous use of the `guards` variable to check if the global default subscriber is set. The new implementation uses `dispatcher::has_been_set`, which provides a simpler and cleaner check.
Closes #189
> Change logging behavior to depend on `log_path`

- src/logging.rs
- Close #194
- Fixed the comment regarding the return type
- Also fixed the comment about the logging behavior, which was previously inaccurate.
> Fix comment on `init_tracing` function.

- CHANGELOG.md
- src/request.rs
- src/subscribe.rs
Update the `connect` method to properly check whether the existing connection has been closed before attempting to reuse it.
Closes #190
> Fix connection behavior after manager restart

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/subscribe.rs
- src/subscribe/tests.rs
- Migrate `bincode` v1 to v2 with `serde` feature
- Update `giganto-client` to rev `47815ca` (adds `start_time` field)
Closes: #232
> Upgrade `bincode` to v2 and update dependencies
