aicers/crusher

- Cargo.toml
- src/client.rs
- src/request.rs
- src/subscribe.rs
> Update quinn 0.8 to 0.9

- Cargo.lock
- Cargo.toml
- src/subscribe.rs
Prints received network event with temporary msg code, source, start
> Add received network event structure

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/model.rs
- src/subscribe.rs
- src/subscribe/tests.rs
Based on the fact that giganto sends events in order of time, this generates time series according to the model's configuration. Close #10
> Generate time series

- src/model.rs
- src/subscribe.rs
> Modify request message for giganto

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/model.rs
- src/request.rs
- src/subscribe.rs
- src/subscribe/tests.rs
- Add oinq, roxy
- Set default start time to 0 when receive policy
Close: #14
> Receive policy from server

- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- src/model.rs
- src/settings.rs
- src/subscribe.rs
- src/subscribe/tests.rs
- tests/config.toml
- Transfer time series data to giganto
- Write last series timestamp to file
Closes: #12
> Transfer generated time series data to giganto

- src/main.rs
- src/request.rs
- src/subscribe.rs
- Fix reconnect logic for REview
- Fix to filter duplicate policy list sent by REview
- Set policy start time using the file in which the last time is saved
Closes: #15, #24
> Modify request/subscribe module

- src/subscribe.rs
> Remove unnecessary attributes

- src/client.rs
- src/request.rs
- src/subscribe.rs
- Modify raw event Stream logic
- Add connection retry logic
Closes: #28
> Receive stream start message from giganto

- src/request.rs
- src/subscribe.rs
> Add Time Series Protocol

- src/subscribe.rs
- src/subscribe/tests.rs
- Add more field to conn, http, dns.
- Modify conn ColumnValue according to conn fields
Close: #37
> Add more fields

- Cargo.lock
- Cargo.toml
- src/model.rs
- src/subscribe.rs
- src/subscribe/tests.rs
- Replace quic communication logic with giganto-client api
- Replace the raw data structure with the structure of giganto
Closes: #41
> Add giganto-client crate

- src/request.rs
Update review protocol version to 0.17.0-alpha.1
> Update review protocol version to 0.17.0-alpha.1

- Cargo.lock
- Cargo.toml
- src/subscribe.rs
- Update giganto protocol version to 0.9.0 (ingest, publish)
- Bump giganto-client from 0.2.0 to 0.3.0
> Update giganto protocol version to 0.9.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/request.rs
- src/subscribe.rs
https://github.com/aicers/giganto/pull/359 에서 FTP Protocol을 지원하여 그에 따라 crusher ftp 요청/수신 부분 추가.
> Add ftp protocol

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/main.rs
- src/request.rs
- src/subscribe.rs
- src/subscribe/tests.rs
- Remove policy in runtime policy list.
- Close giganto publish channel with giganto by id.
Issue: #52
> Add `delete_sampling_policy` api

- README.md
- src/request.rs
Update review handshake protocol version to 0.25.0
> update review protocol version to 0.25.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/request.rs
- src/subscribe.rs
- Add more network data type. (`Mqtt`, `Ldap`, `Tls`, `Smb`, `Nfs`).
Closes: #58
Related issue: #59
> Support new protocols

- Cargo.lock
- Cargo.toml
- src/client.rs
- src/model.rs
- src/subscribe.rs
Fix clippy warning
* Change `with_single_cert()` to `with_client_auth_cert()`
* Bump crates
> Fix clippy warning

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- src/model.rs
- src/request.rs
- src/settings.rs
- src/subscribe.rs
- src/subscribe/tests.rs
- tests/config.toml
- Add get or set giganto address in config file.
- Rename `ingestion` to `ingest`
- Support `RequestCode::ProcessList`.
Close: https://github.com/aicers/crusher/issues/48
Close: https://github.com/aicers/crusher/issues/63
> Support remote control & Process list

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/request.rs
- src/subscribe.rs
> Modify proto header type & Release 0.3.1

- CHANGELOG.md
- README.md
- src/client.rs
- src/request.rs
- src/subscribe.rs
- Changed `REVIEW_PROTOCOL_VERSION` to "0.27.0"
- Changed `PUBLISH_PROTOCOL_VERSION` to "0.17.0"
> Update review/publish handshake version

- CHANGELOG.md
- src/main.rs
- src/request.rs
- src/settings.rs
> Use temporary file to `set_config`

- .github/workflows/ci.yml
- CHANGELOG.md
- src/client.rs
- src/main.rs
- src/model.rs
- src/request.rs
- src/settings.rs
- src/subscribe.rs
- src/subscribe/tests.rs
> Apply group imports by StdExternalCrate

- Cargo.lock
- Cargo.toml
- src/subscribe.rs
- src/subscribe/tests.rs
- Replace lazy-static to LazyLock
- Fix clippy error
Close: #89
> Use LazyLock to replace lazy-static

- Cargo.lock
- Cargo.toml
- src/client.rs
- src/subscribe/tests.rs
> Modify to use ring as the rustls cryptography library option

- README.md
- src/settings.rs
- src/subscribe/tests.rs
> Correct organization info

- src/main.rs
> Apply the log level based on the RUST_LOG value

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- src/settings.rs
- tests/config.toml
- Added the clap crate for parsing CLI arguments.
- Removed corresponding fields from the configuration file.
Close: #111 
Close: #115
> Add CLI arguments for manager server connection

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/request.rs
- src/subscribe.rs
> Rename source to sensor

- .github/workflows/ci.yml
- src/subscribe/tests.rs
- Resolve direct comparison of float values by using `partial_cmp`.
[Clippy link](https://rust-lang.github.io/rust-clippy/master/index.html#float_cmp)
- Resolve slow vector initialization.
[Clippy link](https://rust-lang.github.io/rust-clippy/master/index.html#slow_vector_initialization)
- Make Github CI to run Clippy on test files.
Close: #133
> Fix Clippy errors in tests

- src/main.rs
> Remove misused `unwrap_or_else`

- CHANGELOG.md
- README.md
- src/client.rs
- src/logging.rs
- src/main.rs
- src/request.rs
- src/settings.rs
- src/subscribe.rs
- src/subscribe/tests.rs
~TODO: `last_timestamp_data` will be outdated in the remote mode.
https://github.com/aicers/crusher/issues/113#issuecomment-2544413384~
- Added `get_config` method to `request::Client` to fetch the
configuration from the Manager server.
- Added `enter_minimal_mode`, `try_connect` methods to `request::Client`
to support minimal mode.
- Restructured `main` to support minimal mode.
- Moved `to_cert_chain`, `to_private_key`, `to_ca_certs` functions to
`Certs` struct for modularity.
Close: #112 
Close: #113
```sh
RUST_LOG=info cargo run -- \
-c /Users/jake/Downloads/cluml/aice/crusher/crusher.toml \
--cert /Users/jake/Downloads/cluml/aice/pem/crusher_cert.pem \
--key /Users/jake/Downloads/cluml/aice/pem/crusher_key.pem \
--ca-certs /Users/jake/Downloads/cluml/aice/pem/cert.pem \ …
```
> Fetch configuration from the Manager server

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> Update giganto-client to version 0.22.0

- CHANGELOG.md
> Remove double quotes from dependency version

- CHANGELOG.md
- README.md
- src/main.rs
> Change the format of `--ca-certs` CLI argument

- CHANGELOG.md
- README.md
> Correct the format of `--ca-certs` CLI argument

- src/settings.rs
- src/subscribe.rs
> Change datalake to data store

- CHANGELOG.md
- README.md
- src/logging.rs
From crusher.log to time-series-generator.log.
Closes #165
> Rename the log file

- .cargo/config.toml
- src/logging.rs
Added the environment variable `LOG_FILE_NAME` to the Cargo config file.
Closes #167
> Add env variable to the Cargo config

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> Bump version to 0.6.1

- CHANGELOG.md
- README.md
Rename log file from 'time-series-generator.log' to 'time_series_generator.log'.
Close: #174
> Update CHANGELOG & README

- src/subscribe.rs
> Use pass-by-reference to avoid unnecessary cloning

- CHANGELOG.md
- src/request.rs
> Fix node status update

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/request.rs
This PR is worked on top of https://github.com/aicers/crusher/pull/185
Related: #186
> Bump version to 0.6.2

- src/client.rs
- src/logging.rs
- src/main.rs
- src/request.rs
- src/settings.rs
- src/subscribe.rs
- src/subscribe/tests.rs
- src/time_series.rs
> Minimize unnecessary pub access modifiers

- Cargo.toml
- src/client.rs
- src/logging.rs
- src/main.rs
- src/request.rs
- src/settings.rs
- src/subscribe.rs
- src/subscribe/tests.rs
- src/subscribe/time_series.rs
> Migrate to Rust 2024

- src/main.rs
- src/request.rs
- src/subscribe.rs
> Add logs for audit purposes

- .github/workflows/ci.yml
> Add rustfmt and clippy to rust-toolchain
